### ISSUE TITLE
Квадратное уравнение

### ISSUE THREAD

**Issue by ankutalev** [19214Romanov/nsromanov_19214#1]
1) Зачем Вам отдельный случай на d==0 ? sqrt от 0 - это 0, специальный случай вырожден
2) А вот случаи в духе  0 0 0 , 0 2 2, 0 0 2 игнорируются

**Comment by 19214Romanov** [comment]
Я поправил решение

**Comment by ankutalev** [comment]
Случаи все еще игнорируются ( в исходном комментарии - на эти 3 ввода функция должна выдавать 3 разных значения).
К тому же, теперь у Вас наружу "торчат" вспомогательные функции - спрячьте их, ипользуя конструкции where или let in

**Comment by 19214Romanov** [comment]
> Случаи все еще игнорируются ( в исходном комментарии - на эти 3 ввода функция должна выдавать 3 разных значения).
> К тому же, теперь у Вас наружу "торчат" вспомогательные функции - спрячьте их, ипользуя конструкции where или let in

Учёл замечания, переделал

**Comment by ankutalev** [comment]
Вложенные функции знают про внешние параметры
можно написать d = ... и писать его везде, а не d a b c

И передалйте еще страшные гварды на красивый паттерн матчинг

**Comment by 19214Romanov** [comment]
> 
> 
> Вложенные функции знают про внешние параметры
> можно написать d = ... и писать его везде, а не d a b c
> 
> И передалйте еще страшные гварды на красивый паттерн матчинг

Насчёт использования временных параметров всё понял, исправил.
А насчет исправления гвардов на красивый паттерн матчинг: пока что не пришло осознание.
Нужно отдельно посоветоваться.

**Comment by 19214Romanov** [comment]
Я внес ещё некоторые изменения в код. Надеюсь эти изменения можно считать "красивыми"

**Comment by ankutalev** [comment]
Во, принято
