### ISSUE TITLE
lab o 

### ISSUE THREAD

**Issue by ankutalev** [19214Romanov/nsromanov_19214#3]
https://github.com/19214Romanov/nsromanov_19214/blob/8cb5aa82321722a8db13463aa79c52a38356505f/lists.hs#L26

Вы n раз используете операции last и init , которые работают за O(n) , итого получаете O(n^3).
Реверсить можно и нужно за O(n)

**Comment by 19214Romanov** [comment]
> 
> 
> https://github.com/19214Romanov/nsromanov_19214/blob/8cb5aa82321722a8db13463aa79c52a38356505f/lists.hs#L26
> 
> Вы n раз используете операции last и init , которые работают за O(n) , итого получаете O(n^3).
> Реверсить можно и нужно за O(n)

Переписал данную функцию.

**Comment by ankutalev** [comment]
Стало O(n^2) - append работает за O(n) , Вы делаете его n раз. Можно еще быстрее

**Comment by 19214Romanov** [comment]
> 
> 
> Стало O(n^2) - append работает за O(n) , Вы делаете его n раз. Можно еще быстрее

Сделал reverse' быстрее. Кажется, он уже совсем на пределе))
